# Generated by Django 4.2.13 on 2024-07-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_created_at_category_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
